CREATE TABLE atlas_company (
    atlas_company_id UUID PRIMARY KEY,
    canonical_name VARCHAR(256) NOT NULL,
    unified_credit_code VARCHAR(32),
    registration_no VARCHAR(64),
    company_status VARCHAR(32),
    merged_into_company_id UUID,
    row_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_company_merged_into
        FOREIGN KEY (merged_into_company_id) REFERENCES atlas_company(atlas_company_id),
    CONSTRAINT uq_company_credit_code UNIQUE (unified_credit_code)
);

CREATE TABLE company_identity_binding (
    binding_id UUID PRIMARY KEY,
    atlas_company_id UUID NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    source_entity_id VARCHAR(128) NOT NULL,
    legacy_md5 VARCHAR(64),
    unified_credit_code VARCHAR(32),
    confidence DECIMAL(5,4) NOT NULL,
    binding_status VARCHAR(24) NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE,
    valid_to TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_binding_company
        FOREIGN KEY (atlas_company_id) REFERENCES atlas_company(atlas_company_id),
    CONSTRAINT uq_binding_source UNIQUE (source_system, source_entity_id),
    CONSTRAINT ck_binding_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX idx_binding_legacy_md5 ON company_identity_binding(legacy_md5);
CREATE INDEX idx_binding_credit_code ON company_identity_binding(unified_credit_code);

CREATE TABLE investigation_task (
    task_id UUID PRIMARY KEY,
    task_no VARCHAR(32) NOT NULL,
    intent VARCHAR(32) NOT NULL,
    status VARCHAR(48) NOT NULL,
    atlas_company_id UUID,
    original_prompt TEXT NOT NULL,
    company_query VARCHAR(256) NOT NULL,
    previous_report_file_id VARCHAR(256) NOT NULL,
    operator_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    current_step VARCHAR(64),
    failed_step VARCHAR(64),
    error_code VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_task_company
        FOREIGN KEY (atlas_company_id) REFERENCES atlas_company(atlas_company_id),
    CONSTRAINT uq_task_no UNIQUE (task_no),
    CONSTRAINT uq_task_idempotency UNIQUE (idempotency_key)
);

CREATE INDEX idx_task_status_updated ON investigation_task(status, updated_at);
CREATE INDEX idx_task_company_created ON investigation_task(atlas_company_id, created_at);

CREATE TABLE task_step (
    task_step_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    step_name VARCHAR(64) NOT NULL,
    sequence_no INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_no INTEGER NOT NULL,
    input_hash VARCHAR(64),
    output_ref VARCHAR(512),
    trace_id VARCHAR(64) NOT NULL,
    error_code VARCHAR(64),
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_step_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT uq_step_attempt UNIQUE (task_id, step_name, attempt_no)
);

CREATE TABLE task_event (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload_json TEXT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_event_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id)
);

CREATE INDEX idx_task_event_replay ON task_event(task_id, event_id);

CREATE TABLE data_snapshot (
    snapshot_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    atlas_company_id UUID NOT NULL,
    snapshot_version INTEGER NOT NULL,
    company_facts_json TEXT NOT NULL,
    risk_events_json TEXT NOT NULL,
    source_status_json TEXT NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    frozen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_snapshot_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT fk_snapshot_company
        FOREIGN KEY (atlas_company_id) REFERENCES atlas_company(atlas_company_id),
    CONSTRAINT uq_snapshot_version UNIQUE (task_id, snapshot_version)
);

CREATE TABLE evidence (
    evidence_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    atlas_company_id UUID NOT NULL,
    evidence_type VARCHAR(32) NOT NULL,
    source_provider VARCHAR(64) NOT NULL,
    source_url TEXT,
    normalized_url TEXT,
    title VARCHAR(512) NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    entity_match_status VARCHAR(32) NOT NULL,
    verification_status VARCHAR(32) NOT NULL,
    storage_uri TEXT,
    snippet TEXT,
    raw_metadata_json TEXT,
    CONSTRAINT fk_evidence_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT fk_evidence_company
        FOREIGN KEY (atlas_company_id) REFERENCES atlas_company(atlas_company_id)
);

CREATE INDEX idx_evidence_task_captured ON evidence(task_id, captured_at);
CREATE INDEX idx_evidence_content_hash ON evidence(content_hash);

CREATE TABLE finding (
    finding_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    risk_type VARCHAR(64) NOT NULL,
    title VARCHAR(512) NOT NULL,
    summary TEXT NOT NULL,
    severity VARCHAR(32) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL,
    status VARCHAR(32) NOT NULL,
    model_version VARCHAR(64),
    source_snapshot_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_finding_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT fk_finding_snapshot
        FOREIGN KEY (source_snapshot_id) REFERENCES data_snapshot(snapshot_id),
    CONSTRAINT ck_finding_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE TABLE finding_evidence (
    finding_id UUID NOT NULL,
    evidence_id UUID NOT NULL,
    PRIMARY KEY (finding_id, evidence_id),
    CONSTRAINT fk_finding_evidence_finding
        FOREIGN KEY (finding_id) REFERENCES finding(finding_id),
    CONSTRAINT fk_finding_evidence_evidence
        FOREIGN KEY (evidence_id) REFERENCES evidence(evidence_id)
);

CREATE TABLE risk_score_snapshot (
    score_snapshot_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    data_snapshot_id UUID NOT NULL,
    legacy_score DECIMAL(8,4),
    rule_calculated_score DECIMAL(8,4) NOT NULL,
    event_floor_score DECIMAL(8,4) NOT NULL,
    original_score DECIMAL(8,4) NOT NULL,
    manual_score DECIMAL(8,4) NOT NULL,
    original_risk_level VARCHAR(32) NOT NULL,
    manual_risk_level VARCHAR(32) NOT NULL,
    rule_version VARCHAR(64) NOT NULL,
    engine_version VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    rule_hits_json TEXT NOT NULL,
    calculated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_score_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT fk_score_snapshot
        FOREIGN KEY (data_snapshot_id) REFERENCES data_snapshot(snapshot_id),
    CONSTRAINT ck_score_original CHECK (original_score >= 0 AND original_score <= 10),
    CONSTRAINT ck_score_manual CHECK (manual_score >= 0 AND manual_score <= 10)
);

CREATE TABLE operator_decision (
    decision_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id UUID NOT NULL,
    decision_type VARCHAR(32) NOT NULL,
    before_json TEXT,
    after_json TEXT NOT NULL,
    reason_code VARCHAR(64) NOT NULL,
    reason_text TEXT NOT NULL,
    operator_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_decision_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id)
);

CREATE INDEX idx_decision_task_created ON operator_decision(task_id, created_at);

CREATE TABLE report_version (
    report_id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    atlas_company_id UUID NOT NULL,
    template_version VARCHAR(64) NOT NULL,
    report_version_no INTEGER NOT NULL,
    status VARCHAR(24) NOT NULL,
    previous_report_uri TEXT NOT NULL,
    generated_report_uri TEXT,
    content_hash VARCHAR(64),
    data_snapshot_id UUID NOT NULL,
    score_snapshot_id UUID NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE,
    generated_by VARCHAR(64),
    CONSTRAINT fk_report_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT fk_report_company
        FOREIGN KEY (atlas_company_id) REFERENCES atlas_company(atlas_company_id),
    CONSTRAINT fk_report_snapshot
        FOREIGN KEY (data_snapshot_id) REFERENCES data_snapshot(snapshot_id),
    CONSTRAINT fk_report_score
        FOREIGN KEY (score_snapshot_id) REFERENCES risk_score_snapshot(score_snapshot_id),
    CONSTRAINT uq_report_version UNIQUE (task_id, report_version_no)
);

CREATE TABLE audit_event (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id UUID,
    trace_id VARCHAR(64) NOT NULL,
    actor_type VARCHAR(32) NOT NULL,
    actor_id VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target_type VARCHAR(32) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    payload_digest VARCHAR(64),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_audit_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id)
);

CREATE INDEX idx_audit_task_time ON audit_event(task_id, occurred_at);
CREATE INDEX idx_audit_trace_time ON audit_event(trace_id, occurred_at);
