CREATE TABLE agent_conversation (
    conversation_id UUID PRIMARY KEY,
    operator_id VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    task_id UUID,
    company_query VARCHAR(256),
    previous_report_file_id VARCHAR(256),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_agent_conversation_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id)
);

CREATE INDEX idx_agent_conversation_operator_updated
    ON agent_conversation(operator_id, updated_at);

CREATE TABLE agent_message (
    message_seq BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message_id UUID PRIMARY KEY,
    conversation_id UUID NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    response_type VARCHAR(32),
    parsed_intent VARCHAR(48),
    company_query VARCHAR(256),
    task_id UUID,
    idempotency_key VARCHAR(128) NOT NULL,
    required_inputs_json TEXT NOT NULL,
    suggested_actions_json TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_agent_message_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES agent_conversation(conversation_id),
    CONSTRAINT fk_agent_message_task
        FOREIGN KEY (task_id) REFERENCES investigation_task(task_id),
    CONSTRAINT uq_agent_message_idempotency
        UNIQUE (conversation_id, idempotency_key, role)
);

CREATE INDEX idx_agent_message_conversation_created
    ON agent_message(conversation_id, message_seq);
